version: '3.8'

services:
  dfw_reverseproxy:
    image: eventec.azurecr.io/nginxdfw:1.5
    ports:
      - 80:80
      - 443:443
    networks:
      - dfwnet
networks:
  dfwnet:
    external: true
    name: dfwnet