version: "3.8"

services:
  yarp:
    image: eventec.azurecr.io/yarppsychzdfw:1.4
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    networks:
      - dfwnet
  eventecapi:
    image: eventec.azurecr.io/eventec2024webapi:1.8
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Production
      - SEQ_CONFIG=http://eventec_api_logs:5341/|Yjl5rZPrfUvwoCaSaGIC
      - REDIS_CONFIG=cache:6389|DfwRedisCache|IWfNnSSLL05IoTyv9VVQ
      - POSTGRES_CONFIG=DfwCluster
      - HOSTNAME=$HOSTNAME
      - CLUSTER=dfw_cluster
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
      - WEBHOST=default
    ports:
      - 5008:5000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - dfwnet
  eventec_api_logs:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=brando
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=FAes435kDLuPUnN0drDNoboq+7tc7Ot5POeqMv8+dq8KYAqTSw==
      - SEQ_FIRSTRUN_REQUIREAUTHTENTICATIONFORHTTPINGESTION=False
    volumes:
      - /var/seq/eventec-api-logs:/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - 8005:80
      - 6343:5341
    networks:
      - dfwnet
  cache:
    image: eventec.azurecr.io/redisdfw:1.0
    volumes:
      - /var/redis:/var/lib/redis
    environment:
      - REDIS_PASSWORD=IWfNnSSLL05IoTyv9VVQ
      - REDIS_SERVER=cache
    ports:
      - 6389:6389
    command:
      [
        "sh",
        "-c",
        "redis-server --port 6389 --requirepass $${REDIS_PASSWORD} --maxmemory 20mb --maxmemory-policy allkeys-lru --appendonly yes",
      ]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - dfwnet
networks:
  dfwnet:
    external: true
    name: dfwnet
